"use strict"
var Stars,Utils
Node.prototype.prependChild=function(e){return this.childNodes[1]&&this.insertBefore(e,this.childNodes[1])||this.appendChild(e)},Utils={$:function(e){return document.getElementById(e)},addClassName:function(e,t){return this.hasClassName(e,t)?void 0:e.className=e.className?[e.className,t].join(" "):t},bind:function(e,t,n){var r
try{if(e.addEventListener)return e.addEventListener(t,n,!1)
if(e.attachEvent)return e.attachEvent("on"+t,n)}catch(i){r=i}},hasClassName:function(e,t){return new RegExp("(?:^|\\s+)"+t+"(?:\\s+|$)").test(null!=e?e.className:void 0)},HTTPGet:function(e,t,n){var r,i,s,a
if(null==t&&(t={}),window.XMLHttpRequest?i=new XMLHttpRequest:window.ActiveXObject&&(i=new ActiveXObject("MSXML2.XMLHTTP.3.0")),null!=i){i.onreadystatechange=function(){return 4===i.readyState&&null!=n?n(i.responseText):void 0},a=[]
for(r in t)s=t[r],a.push(""+r+"="+encodeURIComponent(s))
return i.open("GET",""+e+"?"+a.join("&"),!0),i.send(null)}},randomID:function(){return Math.random().toString(36).substr(2,5)},removeClassName:function(e,t){var n
return this.hasClassName(e,t)?(n=e.className,e.className=n.replace(new RegExp("(?:^|\\s+)"+t+"(?:\\s+|$)","g"),"")):void 0},setTimeout:function(e,t){return window.setTimeout(t,e)},setInterval:function(e,t){return window.setInterval(t,e)}},Stars=function(){function e(){this.pathname=window.location.pathname,this.instanceID=Utils.randomID(),this.githubUsername=null,this.getGithubUsername(function(e){return function(){return e.pathname.replace("/","")===e.githubUsername?e.init():void 0}}(this))}return e.prototype.init=function(){return this.setBindings(),this.getLocation(),this.inStarred&&(this.removeSelected(),this.renderContent()),this.getButton()},e.prototype.setBindings=function(){var e,t,n,r,i
for(r=document.getElementsByClassName("tabnav-tab")||[],i=[],t=0,n=r.length;n>t;t++)e=r[t],i.push(Utils.bind(e,"click",function(t){return function(n){return null!=e.getAttribute("href").match(/starred/)?t.renderButton():void 0}}(this)))
return i},e.prototype.getLocation=function(){return this.inStarred=null!=window.location.search.match(/starred/),this.inStarred||this.renderButton(),Utils.setTimeout(2e3,function(e){return function(){return e.getLocation()}}(this))},e.prototype.getGithubUsername=function(e){return chrome.storage.local.get("githubUsername",function(t){return function(n){return(null!=n?n.githubUsername:void 0)?t.githubUsername=n.githubUsername:console.log("no set githubUsername"),"function"==typeof e?e():void 0}}(this))},e.prototype.removeSelected=function(){var e,t,n,r,i,s
for(e=document.getElementsByClassName("tabnav-tab"),s=[],n=0,r=e.length;r>n;n++)t=e[n],s.push("selected"===(null!=(i=t.classList)?i[1]:void 0)?t.classList.remove("selected"):void 0)
return s},e.prototype.getButton=function(){return null==document.getElementById(this.instanceID)&&this.renderButton(),Utils.setTimeout(2e3,function(e){return function(){return e.getButton()}}(this))},e.prototype.renderButton=function(){var e,t,n,r
return null==document.getElementById(this.instanceID)?(e=document.createElement("a"),e.setAttribute("id",this.instanceID),Utils.addClassName(e,"tabnav-tab"),this.inStarred&&Utils.addClassName(e,"selected"),e.setAttribute("href",""+this.pathname+"?tab=starred"),t=document.createElement("span"),Utils.addClassName(t,"octicon octicon-star"),e.appendChild(t),n=document.createTextNode(" Starred"),e.appendChild(n),Utils.bind(e,"click",function(e){return function(t){return null!=t&&"function"==typeof t.preventDefault&&t.preventDefault(),e.inStarred?void 0:window.location=""+e.pathname+"?tab=starred"}}(this)),null!=(r=document.getElementsByClassName("tabnav-tabs"))?r[0].appendChild(e):void 0):Utils.removeClassName(document.getElementById(this.instanceID),"selected")},e.prototype.renderContent=function(){var e,t,n,r,i,s
return r=null!=(s=document.getElementsByClassName("tab-content"))?s[0]:void 0,r.innerHTML="",this.githubUsername?(i=document.createElement("ul"),Utils.addClassName(i,"repo-list"),t={per_page:9999999},Utils.HTTPGet("https://api.github.com/users/"+this.githubUsername+"/starred",t,function(t){return function(n){var s,a,o,u,l,d
if(null!=n){for(n=JSON.parse(n),d=n||[],u=0,l=d.length;l>u;u++)a=d[u],s={description:a.description||"",name:a.name||"",owner:a.owner.login||"",ownerURL:a.owner.html_url||"",url:a.html_url||""},o=t.createRepositoryElement(s),i.appendChild(o)
return r.appendChild(i)}return e=t.getMessage("You are not set star to any repository yet."),r.appendChild(e)}}(this))):(e=document.createTextNode("Please configure your Github username on "),n=document.createElement("strong"),n.innerHTML="Preferences &raquo; Extensions &raquo; Github stars",e.appendChild(n),r.appendChild(e))},e.prototype.getMessage=function(e,t){var n
return null==t&&(t="warn"),n=document.createElement("div"),n.setAttribute("class","flash flash-"+t),n.innerHTML=e||"",n},e.prototype.createRepositoryElement=function(e){var t,n,r,i,s,a
return null==e&&(e={}),e?(a=document.createElement("li"),Utils.addClassName(a,"repo-list-item"),n=document.createElement("h3"),Utils.addClassName(n,"repo-list-name"),r=document.createElement("a"),r.setAttribute("href",e.url),r.innerHTML=e.name,n.appendChild(r),t=document.createElement("p"),Utils.addClassName(t,"repo-list-description"),t.innerHTML=e.description,i=document.createElement("p"),Utils.addClassName(i,"repo-list-meta"),s=document.createElement("a"),s.setAttribute("href",e.ownerURL),s.innerHTML=e.owner,i.innerHTML="Owner ",i.appendChild(s),a.appendChild(n),a.appendChild(t),a.appendChild(i),a):void 0},e}(),document.addEventListener("DOMContentLoaded",new Stars)
