// Generated by CoffeeScript 1.8.0
chrome.runtime.onInstalled.addListener(function(details) {
  if ((details != null ? details.reason : void 0) === 'install') {
    if (chrome.runtime.openOptionsPage) {
      return chrome.runtime.openOptionsPage();
    } else {
      return window.open(chrome.runtime.getURL('options/index.html'));
    }
  }
});
