"use strict"
var Options,Utils
Node.prototype.prependChild=function(t){return this.childNodes[1]&&this.insertBefore(t,this.childNodes[1])||this.appendChild(t)},Utils={$:function(t){return document.getElementById(t)},bind:function(t,e,n){var i
try{if(t.addEventListener)return t.addEventListener(e,n,!1)
if(t.attachEvent)return t.attachEvent("on"+e,n)}catch(s){i=s}},insertAfter:function(t,e){return e.parentNode.insertBefore(t,e.nextSibling)},setTimeout:function(t,e){return window.setTimeout(e,t)},trigger:function(t,e){var n
return e?(n=document.createEvent("HTMLEvents"),n.initEvent(e,!0,!1),null!=t&&"function"==typeof t.dispatchEvent?t.dispatchEvent(n):void 0):void 0}},Options=function(){function t(){var t
this.UI={button:{save:Utils.$("apply-settings"),reset:Utils.$("reset-settings")},input:{username:Utils.$("github-username")},section:null!=(t=document.getElementsByTagName("section"))?t[0]:void 0},this.init()}return t.prototype.init=function(){return this.restoreOptions(),this.setBindings()},t.prototype.setBindings=function(){return Utils.bind(this.UI.button.save,"click",function(t){return function(){var e
return e=t.UI.input.username.value,e?t.saveOptions(e):t.showMessage("Please enter your github username.",1e4)}}(this)),Utils.bind(this.UI.button.reset,"click",function(t){return function(){return t.saveOptions()}}(this)),Utils.bind(this.UI.input.username,"keydown",function(t){return function(e){return e.wihch||13===e.keyCode?Utils.trigger(t.UI.button.save,"click"):void 0}}(this))},t.prototype.saveOptions=function(t){return null==t&&(t=""),chrome.storage.sync.set({githubUsername:t},function(e){return function(){return e.UI.input.username.value=t,e.showMessage("Options saved.",5e3)}}(this)),chrome.storage.local.set({githubUsername:t})},t.prototype.restoreOptions=function(){return chrome.storage.sync.get({githubUsername:""},function(t){return function(e){return t.UI.input.username.value=e.githubUsername||""}}(this))},t.prototype.showMessage=function(t,e){var n
return this.removeMessage(),n=document.createElement("div"),n.setAttribute("class","message"),n.innerHTML=t||"",Utils.insertAfter(n,this.UI.section.previousElementSibling),e?Utils.setTimeout(e,function(t){return function(){return t.removeMessage()}}(this)):void 0},t.prototype.removeMessage=function(){var t,e
return null!=(t=document.getElementsByClassName("message"))&&null!=(e=t[0])&&"function"==typeof e.remove?e.remove():void 0},t}(),document.addEventListener("DOMContentLoaded",new Options)
